In [81]:
from sklearn import datasets
from sklearn.datasets import load_iris
import pandas as pd
#from sklearn.decomposition import PCA
import numpy as np
#import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


#data = pd.read_csv('../input/Iris.csv')

#Type of the iris dataset


In [82]:
irisset=load_iris()
type(irisset)

sklearn.utils.Bunch

#Shape of the iris data
#Printing the iris data

In [83]:
print(irisset.data)
irisset.data.shape

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

(150, 4)

#Data Type of the individual element

In [84]:
irisset.data.dtype

dtype('float64')

#No.of dimensions of the iris dataset

In [85]:
irisset.data.ndim

2

#Nmaes of the features

In [86]:
print(irisset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


#Target values

In [87]:
print(irisset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#Target Names

In [88]:
print(irisset.target_names)

['setosa' 'versicolor' 'virginica']


#Converting to dataframe

In [89]:
iris=pd.DataFrame(irisset.data,columns=irisset.feature_names)

In [107]:
iris=iris.rename(columns={"feature_name ": "featuresiris"})
iris['target_names']=irisset.target

In [108]:
iris.head(100)

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target_names
0                 5.1               3.5  ...               0.2             0
1                 4.9               3.0  ...               0.2             0
2                 4.7               3.2  ...               0.2             0
3                 4.6               3.1  ...               0.2             0
4                 5.0               3.6  ...               0.2             0
..                ...               ...  ...               ...           ...
95                5.7               3.0  ...               1.2             1
96                5.7               2.9  ...               1.3             1
97                6.2               2.9  ...               1.3             1
98                5.1               2.5  ...               1.1             1
99                5.7               2.8  ...               1.3             1

[100 rows x 5 columns]

#iris data info

In [91]:
iris.info

<bound method DataFrame.info of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]>

In [92]:
iris.describe

<bound method NDFrame.describe of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]>

#type of the irisdataset

In [93]:
type(iris)

pandas.core.frame.DataFrame

In [94]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

#correlation of each feature

In [95]:
iris.corr()

sepal length (cm)  ...  petal width (cm)
sepal length (cm)           1.000000  ...          0.817941
sepal width (cm)           -0.117570  ...         -0.366126
petal length (cm)           0.871754  ...          0.962865
petal width (cm)            0.817941  ...          1.000000

[4 rows x 4 columns]

#Checking for the null values

In [96]:
iris.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [99]:
iris.shape

(150, 4)

#Separating features and target labels

In [112]:
X_iris=iris.iloc[:, :-1]
X_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [122]:
from sklearn.preprocessing import LabelEncoder
y_iris=iris.iloc[:,-1]
gender_encoder = LabelEncoder()
y_iris = gender_encoder.fit_transform(y_iris)
y_iris


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#Standardisation

In [113]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X_iris= scaler.transform(X)

#Splitting the test and train

In [123]:
from sklearn.model_selection import train_test_split
X_iris_train, X_iris_test, y_iris_train, y_iris_test = train_test_split(X_iris, y_iris, test_size=0.4, random_state=0)


In [152]:
print(X_iris_train)

[[ 1.89829664e-01  7.88807586e-01  4.21733708e-01  5.27406285e-01]
 [-1.26418478e+00  9.82172869e-02 -1.22655167e+00 -1.31544430e+00]
 [-5.25060772e-02 -8.22569778e-01  7.62758269e-01  9.22302838e-01]
 [-2.94841818e-01 -8.22569778e-01  2.51221427e-01  1.32509732e-01]
 [-2.94841818e-01 -3.62176246e-01 -8.98031345e-02  1.32509732e-01]
 [-4.16009689e-01 -1.28296331e+00  1.37546573e-01  1.32509732e-01]
 [ 3.10997534e-01 -1.31979479e-01  4.78571135e-01  2.64141916e-01]
 [ 1.64384411e+00  3.28414053e-01  1.27429511e+00  7.90670654e-01]
 [-6.58345429e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [ 6.74501145e-01 -8.22569778e-01  8.76433123e-01  9.22302838e-01]
 [-1.73673948e-01 -1.31979479e-01  2.51221427e-01  8.77547895e-04]
 [-5.37177559e-01  7.88807586e-01 -1.16971425e+00 -1.31544430e+00]
 [-1.73673948e-01  3.09077525e+00 -1.28338910e+00 -1.05217993e+00]
 [ 1.28034050e+00  9.82172869e-02  6.49083415e-01  3.95774101e

#Tuning SVM hyperparameters by using GridSearchCV with cross validation

In [156]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
svc=SVC() #Default hyperparameters
svc.fit(X_iris_train,y_iris_train)
y_iris_pred= svc.predict(X_iris_test)

In [157]:
print(classification_report(y_iris_test,y_iris_pred))
print(confusion_matrix(y_iris_test,y_iris_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.88      0.96      0.92        23
           2       0.95      0.86      0.90        21

    accuracy                           0.93        60
   macro avg       0.94      0.94      0.94        60
weighted avg       0.94      0.93      0.93        60

[[16  0  0]
 [ 0 22  1]
 [ 0  3 18]]


In [133]:
from sklearn.model_selection import cross_val_score
svc=SVC(kernel='rbf',gamma=0.001)
data_scores = cross_val_score(svc, X_iris, y_iris, cv=10, scoring='accuracy') #cv is cross validation
print(data_scores)
print(data_scores.mean())

[0.73333333 0.86666667 0.93333333 0.86666667 0.8        0.86666667
 0.86666667 0.86666667 0.93333333 0.86666667]
0.8600000000000001


In [135]:
svc=SVC(kernel='rbf')
data_scores = cross_val_score(svc, X_iris, y_iris, cv=10, scoring='accuracy') #cv is cross validation
print(data_scores)
print(data_scores.mean())

[1.         0.93333333 1.         0.93333333 1.         0.93333333
 0.86666667 1.         1.         1.        ]
0.9666666666666666


#Accuracy Score

In [161]:
from sklearn.metrics import accuracy_score
print('accuracy : ',accuracy_score(y_iris_pred,y_iris_test))

accuracy :  0.9333333333333333


#RMSE

In [159]:
from sklearn.metrics import mean_squared_error
import math
mse = mean_squared_error(y_iris_pred , y_iris_test)
rmse = math.sqrt(mse)
print(rmse)

0.2581988897471611


In [164]:
g2 = SVC( kernel = 'rbf' ,random_state=1 , gamma = 0.008 , C = 1)
g2.fit(X_iris_train , y_iris_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.008, kernel='rbf',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

#Accuracy

In [165]:
from sklearn.metrics import accuracy_score
classifier_prediction = g2.predict(X_iris_test)
print(accuracy_score(y_iris_test , classifier_prediction)*100)

83.33333333333334


#GridSearch

In [160]:
from sklearn.model_selection import GridSearchCV
grid={'C':[0.1,1,10,100],'gamma':[1,0.1,0.01,0.001]}
g = GridSearchCV(SVC(),grid,refit=True,verbose=4)
g.fit(X_iris_train,y_iris_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.944, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.722, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.889, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.944, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.944, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.889, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ...........

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s


[CV] .................. C=100, gamma=0.001, score=1.000, total=   0.0s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=1.000, total=   0.0s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.944, total=   0.0s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.944, total=   0.0s


[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    0.2s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=4)

In [167]:
print(g.best_estimator_)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [183]:
g_predictions = g.predict(X_iris_test)
print(confusion_matrix(y_iris_test,g_predictions))
print(classification_report(y_iris_test,g_predictions))

[[16  0  0]
 [ 0 23  0]
 [ 0  4 17]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.85      1.00      0.92        23
           2       1.00      0.81      0.89        21

    accuracy                           0.93        60
   macro avg       0.95      0.94      0.94        60
weighted avg       0.94      0.93      0.93        60



#K-Nearest Neighbours

In [178]:
from sklearn.neighbors import KNeighborsClassifier

classifiers = KNeighborsClassifier(n_neighbors = 9)
classifiers.fit(X_iris_train , y_iris_train)

y_iris_pred = classifiers.predict(X_iris_test)

#Printing the Prediction values

In [180]:
print(classification_report(y_iris_test , y_iris_pred))
print(confusion_matrix(y_iris_test , y_iris_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.88      0.96      0.92        23
           2       0.95      0.86      0.90        21

    accuracy                           0.93        60
   macro avg       0.94      0.94      0.94        60
weighted avg       0.94      0.93      0.93        60

[[16  0  0]
 [ 0 22  1]
 [ 0  3 18]]


#Accuracy

In [185]:
from sklearn.metrics import accuracy_score
print('accuracy :' , accuracy_score(y_iris_pred , y_iris_test))

accuracy : 0.9333333333333333


#RF Regressor

In [186]:
from sklearn.ensemble import RandomForestRegressor
Randomf = RandomForestRegressor(random_state = 8)

from pprint import pprint
 
pprint(Randomf.get_params())

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 8,
 'verbose': 0,
 'warm_start': False}


#Randomized Search

In [194]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.datasets import load_iris
irisset = load_iris()
X_iris=irisset.data
y_iris=irisset.target
z_range=list(range(1,31))
options=['uniform', 'distance']
param_dist = dict(n_neighbors=z_range, weights=options)
KNN = KNeighborsClassifier(n_neighbors = 1)
rand = RandomizedSearchCV(KNN, param_dist, cv=10, scoring='accuracy', n_iter=10, random_state=5)
rand.fit(X_iris, y_iris)
print(rand.best_scores_)
print(rand.best_params_)
best_scores=[]
for i in range(20):
    rand = RandomizedSearchCV(knn, param_dist, cv=10, scoring='accuracy', n_iter=10)
    rand.fit(X_iris, y_iris)
    best_scores.append(round(rand.best_scores,3))
print(best_scores)
print(best_scores.mean())

AttributeError: ignored